# Built by EnergyCraft v1.3.0-A
# 
# For all help, see online documentation

check-interval: 1
max-stack-condense: 4
permission-to-use: false
broadcast-messages: true
level1: GOLD_BLOCK-30%
level2: EMERALD_BLOCK-18%
level3: DIAMOND_BLOCK-5%
level4: GLOWSTONE-0%