# ID - DAMAGE_VALUE :  EMC
# ID-A MEANS ALL DAMAGE VALUES (IE, WOOL)
# ID-X MEANS ITEM CAN BE DAMAGED AND WILL USE A PERCENTAGE OF TOTAL EMC


VERSION: 1.5.0
'AIR-0': 0
'STONE-0': 1
'GRASS_BLOCK-0': 1
'DIRT-0': 1
'COBBLESTONE-0': 1
'ACACIA_PLANKS-0': 8
'BIRCH_PLANKS-0': 8
'DARK_OAK_PLANKS-0': 8
'JUNGLE_PLANKS-0': 8
'OAK_PLANKS-0': 8
'SPRUCE_PLANKS-0': 8
'ACACIA_BOAT-0': 32
'ACACIA_SAPLING-0': 32
'BAMBOO_SAPLING-0': 32
'BIRCH_SAPLING-0': 32
'DARK_OAK_SAPLING-0': 32
'JUNGLE_SAPLING-0': 32
'SAND-0': 1
'GRAVEL-0': 4
'GOLD_ORE-0': 2048
'IRON_ORE-0': 256
'COAL_ORE-0': 128
'ACACIA_LOG-0': 32
'BIRCH_LOG-0': 32
'DARK_OAK_LOG-0': 32
'JUNGLE_LOG-0': 32
'OAK_LOG-0': 32
'SPRUCE_LOG-0': 32
'STRIPPED_ACACIA_LOG-0': 32
'STRIPPED_BIRCH_LOG-0': 32
'STRIPPED_DARK_OAK_LOG-0': 32
'STRIPPED_JUNGLE_LOG-0': 32
'STRIPPED_OAK_LOG-0': 32
'STRIPPED_SPRUCE_LOG-0': 32
'ACACIA_LEAVES-0': 1
'BIRCH_LEAVES-0': 1
'DARK_OAK_LEAVES-0': 1
'JUNGLE_LEAVES-0': 1
'OAK_LEAVES-0': 1
'SPRUCE_LEAVES-0': 1
'BLACK_STAINED_GLASS-0': 1
'BLUE_STAINED_GLASS-0': 1
'BROWN_STAINED_GLASS-0': 1
'CYAN_STAINED_GLASS-0': 1
'GLASS-0': 1
'GRAY_STAINED_GLASS-0': 1
'GREEN_STAINED_GLASS-0': 1
'LIGHT_BLUE_STAINED_GLASS-0': 1
'LIGHT_GRAY_STAINED_GLASS-0': 1
'LIME_STAINED_GLASS-0': 1
'MAGENTA_STAINED_GLASS-0': 1
'ORANGE_STAINED_GLASS-0': 1
'PINK_STAINED_GLASS-0': 1
'PURPLE_STAINED_GLASS-0': 1
'RED_STAINED_GLASS-0': 1
'WHITE_STAINED_GLASS-0': 1
'YELLOW_STAINED_GLASS-0': 1
'LAPIS_ORE-0': 864
'LAPIS_BLOCK-0': 7776
'DISPENSER-0': 119
'CHISELED_RED_SANDSTONE-0': 4
'CHISELED_SANDSTONE-0': 4
'CUT_RED_SANDSTONE-0': 4
'RED_SANDSTONE-0': 4
'SANDSTONE-0': 4
'SMOOTH_RED_SANDSTONE-0': 4
'SMOOTH_SANDSTONE-0': 4
'NOTE_BLOCK-0': 128
'POWERED_RAIL-0': 2048
'DETECTOR_RAIL-0': 256
'STICKY_PISTON-0': 372
'COBWEB-0': 12
'GRASS-0': 1
'DEAD_BUSH-0': 1
'PISTON-0': 348
'BLACK_WOOL-0': 48
'BLUE_WOOL-0': 48
'BROWN_WOOL-0': 48
'CYAN_WOOL-0': 48
'GRAY_WOOL-0': 48
'GREEN_WOOL-0': 48
'LIGHT_BLUE_WOOL-0': 48
'LIGHT_GRAY_WOOL-0': 48
'LIME_WOOL-0': 48
'MAGENTA_WOOL-0': 48
'ORANGE_WOOL-0': 48
'PINK_WOOL-0': 48
'PURPLE_WOOL-0': 48
'RED_WOOL-0': 48
'WHITE_WOOL-0': 48
'YELLOW_WOOL-0': 48
'DANDELION-0': 16
'ROSE-0': 16
'BROWN_MUSHROOM-0': 32
'RED_MUSHROOM-0': 32
'GOLD_BLOCK-0': 18432
'IRON_BLOCK-0': 2304
'STONE_SLAB-0': 1
'CUT_RED_SANDSTONE_SLAB-0': 4
'CUT_SANDSTONE_SLAB-0': 4
'RED_SANDSTONE_SLAB-0': 4
'SANDSTONE_SLAB-0': 4
'SMOOTH_RED_SANDSTONE_SLAB-0': 4
'SMOOTH_SANDSTONE_SLAB-0': 4
'ACACIA_SLAB-0': 8
'ANDESITE_SLAB-0': 8
'BIRCH_SLAB-0': 8
'DARK_OAK_SLAB-0': 8
'JUNGLE_SLAB-0': 8
'OAK_SLAB-0': 8
'PETRIFIED_OAK_SLAB-0': 8
'SPRUCE_SLAB-0': 8
'COBBLESTONE_SLAB-3': 1
'BRICK_SLAB-4': 256
'SMOOTH_STONE_SLAB-5': 0.5
'BRICKS-0': 256
'BOOKSHELF-0': 336
'MOSSY_COBBLESTONE-0': 145
'OBSIDIAN-0': 64
'TORCH-0': 9
'CHEST-0': 64
'DIAMOND_ORE-0': 8192
'DIAMOND-0': 8192
'DIAMOND_BLOCK-0': 73728
'CRAFTING_TABLE-0': 32
'FURNACE-0': 8
'LADDER-0': 14
'RAIL-0': 96
'LEVER-0': 5
'REDSTONE_ORE-0': 64
'REDSTONE_TORCH-0': 68
'ACACIA_BUTTON-0': 1
'BIRCH_BUTTON-0': 1
'DARK_OAK_BUTTON-0': 1
'JUNGLE_BUTTON-0': 1
'OAK_BUTTON-0': 1
'SPRUCE_BUTTON-0': 1
'STONE_BUTTON-0': 1
'BLUE_ICE-0': 1
'FROSTED_ICE-0': 1
'ICE-0': 1
'SNOW_BLOCK-0': 4
'CACTUS-0': 8
'CLAY-0': 256
'JUKEBOX-0': 8256
'ACACIA_FENCE-0': 12
'BIRCH_FENCE-0': 12
'DARK_OAK_FENCE-0': 12
'JUNGLE_FENCE-0': 12
'OAK_FENCE-0': 12
'SPRUCE_FENCE-0': 12
'PUMPKIN-0': 144
'NETHERRACK-0': 1
'SOUL_SAND-0': 49
'GLOWSTONE-0': 1536
'JACK_O_LANTERN-0': 144
'ACACIA_TRAPDOOR-0': 24
'BIRCH_TRAPDOOR-0': 24
'DARK_OAK_TRAPDOOR-0': 24
'JUNGLE_TRAPDOOR-0': 24
'OAK_TRAPDOOR-0': 24
'SPRUCE_TRAPDOOR-0': 24
'STONE_BRICKS-0': 1
'IRON_BARS-0': 96
'BLACK_STAINED_GLASS_PANE-0': 0.375
'BLUE_STAINED_GLASS_PANE-0': 0.375
'BROWN_STAINED_GLASS_PANE-0': 0.375
'CYAN_STAINED_GLASS_PANE-0': 0.375
'GLASS_PANE-0': 0.375
'GRAY_STAINED_GLASS_PANE-0': 0.375
'GREEN_STAINED_GLASS_PANE-0': 0.375
'LIGHT_BLUE_STAINED_GLASS_PANE-0': 0.375
'LIGHT_GRAY_STAINED_GLASS_PANE-0': 0.375
'LIME_STAINED_GLASS_PANE-0': 0.375
'MAGENTA_STAINED_GLASS_PANE-0': 0.375
'ORANGE_STAINED_GLASS_PANE-0': 0.375
'PINK_STAINED_GLASS_PANE-0': 0.375
'PURPLE_STAINED_GLASS_PANE-0': 0.375
'RED_STAINED_GLASS_PANE-0': 0.375
'WHITE_STAINED_GLASS_PANE-0': 0.375
'YELLOW_STAINED_GLASS_PANE-0': 0.375
'MELON-0': 144
'VINE-0': 1
'ACACIA_FENCE_GATE-0': 32
'BIRCH_FENCE_GATE-0': 32
'DARK_OAK_FENCE_GATE-0': 32
'JUNGLE_FENCE_GATE-0': 32
'OAK_FENCE_GATE-0': 32
'SPRUCE_FENCE_GATE-0': 32
'MYCELIUM-0': 1
'LILY_PAD-0': 16
'NETHER_BRICK-0': 4
'NETHER_BRICK_FENCE-0': 24
'ENCHANTING_TABLE-0': 16736
'END_STONE-0': 1
'DRAGON_EGG-0': 139264
'REDSTONE_LAMP-0': 1792
'EMERALD_ORE-0': 0
'ENDER_CHEST-0': 2304
'TRIPWIRE_HOOK-0': 268
'EMERALD_BLOCK-0': 0
'BEACON-0': 0
'COBBLESTONE_WALL-0': 1
'MOSSY_COBBLESTONE_WALL-0': 145
'ACACIA_BUTTON-0': 8
'BIRCH_BUTTON-0': 8
'DARK_OAK_BUTTON-0': 8
'JUNGLE_BUTTON-0': 8
'OAK_BUTTON-0': 8
'SPRUCE_BUTTON-0': 8
'ANVIL-0': 7936
'CHIPPED_ANVIL-0': 0
'DAMAGED_ANVIL-0': 0
'IRON_SHOVEL-X': 264
'IRON_PICKAXE-X': 776
'IRON_AXE-X': 776
'FLINT_AND_STEEL-X': 260
'APPLE-0': 128
'BOW-X': 48
'ARROW-0': 14
'COAL-0': 128
'CHARCOAL-0': 32
'IRON_INGOT-0': 256
'GOLD_INGOT-0': 2048
'IRON_SWORD-X': 516
'WOODEN_SWORD-X': 20
'WOODEN_SHOVEL-X': 16
'WOODEN_PICKAXE-X': 32
'WOODEN_AXE-X': 32
'STONE_SWORD-X': 6
'STONE_SHOVEL-X': 9
'STONE_PICKAXE-X': 11
'STONE_AXE-X': 11
'DIAMOND_SWORD-X': 16388
'DIAMOND_SHOVEL-X': 8200
'DIAMOND_PICKAXE-X': 24584
'DIAMOND_AXE-X': 24584
'GOLDEN_SWORD-X': 4100
'GOLDEN_SHOVEL-X': 2056
'GOLDEN_PICKAXE-X': 6152
'GOLDEN_AXE-X': 6152
'WOODEN_HOE-X': 24
'STONE_HOE-X': 10
'IRON_HOE-X': 520
'DIAMOND_HOE-X': 16392
'GOLDEN_HOE-X': 4104
'LEATHER_HELMET-X': 320
'LEATHER_CHESTPLATE-X': 512
'LEATHER_LEGGINGS-X': 448
'LEATHER_BOOTS-X': 256
'IRON_HELMET-X': 1280
'IRON_CHESTPLATE-X': 2048
'IRON_LEGGINGS-X': 1792
'IRON_BOOTS-X': 1024
'DIAMOND_HELMET-X': 40960
'DIAMOND_CHESTPLATE-X': 65536
'DIAMOND_LEGGINGS-X': 57344
'DIAMOND_BOOTS-X': 32768
'GOLDEN_HELMET-X': 10240
'GOLDEN_CHESTPLATE-X': 16384
'GOLDEN_LEGGINGS-X': 14336
'GOLDEN_BOOTS-X': 8192
'GOLDEN_APPLE-0': 1944
'ENCHANTED_GOLDEN_APPLE-0': 147584
'STICK-0': 4
'STRING-0': 12
'FEATHER-0': 48
'GUNPOWDER-0': 192
'WHEAT_SEEDS-0': 16
'WHEAT-0': 24
'BREAD-0': 72
'FLINT-0': 4
'COOKED_PORKCHOP-0': 64
'BUCKET-0': 768
'WATER_BUCKET-0': 769
'LAVA_BUCKET-0': 832
'MINECART-0': 1280
'SADDLE-0': 192
'REDSTONE-0': 64
'LEATHER-0': 64
'MILK-0': 833
'BRICK-0': 64
'CLAY_BALL-0': 64
'REEDS-0': 32
'PAPER-0': 32
'BOOK-0': 96
'SLIME_BALL-0': 24
'EGG-0': 32
'FISHING_ROD-X': 12
'COD-0': 64
'PUFFERFISH-0': 64
'TROPICAL_FISH-0': 64
'SALMON-0': 64
'COOKED_SALMON-0': 64
'COOKED_COD-0': 64
'BLACK_DYE-0': 8
'BLUE_DYE-0': 8
'BROWN_DYE-0': 8
'CYAN_DYE-0': 8
'GRAY_DYE-0': 8
'GREEN_DYE-0': 8
'LIGHT_BLUE_DYE-0': 8
'LIGHT_GRAY_DYE-0': 8
'LIME_DYE-0': 8
'MAGENTA_DYE-0': 8
'ORANGE_DYE-0': 8
'PINK_DYE-0': 8
'PURPLE_DYE-0': 8
'RED_DYE-0': 8
'WHITE_DYE-0': 8
'YELLOW_DYE-0': 32
'INK_SAC-0': 8
'BONE-0': 96
'SUGAR-0': 32
'CAKE-0': 384
'BED-0': 144
'REPEATER-0': 203
'COOKIE-0': 22
'FILLED_MAP-0': 1344
'SHEARS-X': 512
'MELON_SLICE-0': 16
'PUMPKIN_SEEDS-0': 36
'MELON_SEEDS-0': 16
'BEEF-0': 64
'COOKED_BEEF-0': 64
'CHICKEN-0': 64
'COOKED_CHICKEN-0': 64
'ROTTEN_FLESH-0': 24
'ENDER_PEARL-0': 1024
'BLAZE_ROD-0': 1536
'GHAST_TEAR-0': 4096
'GOLD_NUGGET-0': 227
'NETHER_WART-0': 24
'GLASS_BOTTLE-0': 1
'SPIDER_EYE-0': 128
'FERMENTED_SPIDER_EYE-0': 192
'BLAZE_POWDER-0': 768
'MAGMA_CREAM-0': 792
'BREWING_STAND-0': 1539
'CAULDRON-0': 1792
'ENDER_EYE-0': 1792
'GLISTERING_MELON_SLICE-0': 243
'FIRE_CHARGE-0': 362
'WRITABLE_BOOK-0': 152
'WRITTEN_BOOK-0': 152
'ITEM_FRAME-0': 96
'FLOWER_POT-0': 192
'MAP-0': 1344
'PUMPKIN_PIE-0': 208
'MUSIC_DISC_11-0': 2048
'MUSIC_DISC_13-0': 2048
'MUSIC_DISC_BLOCKS-0': 2048
'MUSIC_DISC_CAT-0': 2048
'MUSIC_DISC_CHIRP-0': 2048
'MUSIC_DISC_FAR-0': 2048
'MUSIC_DISC_MALL-0': 2048
'MUSIC_DISC_MELLOHI-0': 2048
'MUSIC_DISC_STAL-0': 2048
'MUSIC_DISC_STRAD-0': 2048
'MUSIC_DISC_WAIT-0': 2048
'MUSIC_DISC_WARD-0': 2048
