name: EnergyCraft
main: com.github.vsams14.energycraft.Main
version: 1.1.6
authors: [vsams14, Samkio]
commands:
   emc:
      description: Checks the EMC value of the item in hand.
      usage: /emc