name: EnergyCraft
main: com.github.vsams14.energycraft.Main
version: 1.2.4
authors: [vsams14, Samkio]
commands:
   emc:
      description: Checks the EMC value of the item in hand.
      usage: /emc
      
permissions:
   ec.*:
      description: Gives access to all EnergyCraft nodes.
      children:
         ec.build: true
         ec.edit: true
      
   ec.build:
      description: Allows building/breaking a converter.
      
   ec.edit:
      description: Allows editing of others' converters.