package com.github.vsams14.energycraft;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import org.bukkit.inventory.ItemStack;

public class Config {
	private Main main;

	public Config(Main main) {
		this.main = main;
	}

	public int getEMC(ItemStack i) {
		if (i != null) {
			main.reloadConfig();
			String s = i.getTypeId() + "-" + i.getDurability();
			String z = main.getConfig().getString(s);
			int dur;
			
			if (z == null) {
				s = i.getTypeId() + "-A";
				z = main.getConfig().getString(s);
				if (z == null) {
					s = i.getTypeId() + "-X";
					z = main.getConfig().getString(s);
					if (z == null) {
						return 0;
					}
					main.log.info(s + " is a variable item");
					dur = Integer.parseInt(z);
					float ddur = 1.0F - Float.valueOf(i.getDurability()) / getMaxDur(i, dur);
					main.log.info("Condensed " + s + " for " + (int)(dur * ddur) + " EMC");
					return (int)(dur * ddur);
				}

				dur  = Integer.parseInt(z);
				return dur;
			}

			dur = Integer.parseInt(z);
			return dur;
		}

		return 0;
	}

	public float getMaxDur(ItemStack i, int dd) {
		switch (i.getTypeId()) {
		case 276:
			return 1562.0F;
		case 277:
			return 1562.0F;
		case 278:
			return 1562.0F;
		case 279:
			return 1562.0F;
		case 293:
			return 1562.0F;
		case 310:
			return 364.0F;
		case 311:
			return 529.0F;
		case 312:
			return 496.0F;
		case 313:
			return 430.0F;
		}
		return 1.0F;
	}

	public void loadCon() {
		File in = new File(main.getDataFolder(), File.separator + "condensers.sav");
		try {
			BufferedReader readFile = new BufferedReader(new FileReader(in));
			String s;
			while ((s = readFile.readLine()) != null) {
				if (s.contains(":")) {
					main.util.stringToCondenser(s);
				}
			}
			readFile.close();
		} catch (FileNotFoundException e) {
			main.log.severe("condensers.sav could not be found! Make sure that this is not an error!");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public void saveCon() {
		File out = new File(main.getDataFolder(), File.separator + "condensers.sav");
		try {
			BufferedWriter fileWriter = new BufferedWriter(new FileWriter(out));
			fileWriter.write("# DO NOT EDIT THIS FILE!\r\n");
			fileWriter.flush();
			for (String s : main.con.keySet()) {
				Condenser c = (Condenser)main.con.get(s);
				fileWriter.write(c.saveString() + "\r\n");
				fileWriter.flush();
			}
			fileWriter.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}